### ISSUE TITLE
-p argument missing

### ISSUE THREAD

**Issue by action-simon** [akeneo-labs/DataGeneratorBundle#1]
Hello,

I installed DataGeneratorBundle but the -p argument is missing and I cannot create test products.
![bildschirmfoto 2014-10-29 um 12 27 15](https://cloud.githubusercontent.com/assets/2743242/4824814/9f7d611a-5f5e-11e4-9fc0-99b747f33553.png)

**Comment by jmleroux** [comment]
Hello action-simon,

The correct command should be : 
`php app/console pim:generate-data product 1000 /tmp/products.csv`

PR to come ;)

**Comment by BitOne** [comment]
Thanks @jmleroux for the doc update !
